spring:
  application:
    name: PriceRader

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

naver:
  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}
  search:
    base_url: ${NAVER_SEARCH_BASER_URL}
    shop:
      json: ${NAVER_SEARCH_SHOP_JSON}


jwt:
  access:
    key: ${JWT_ACCESS_KEY}
  refresh:
    key: ${JWT_REFRESH_KEY}